#	Writen by: Oscar Bergström
#  	https://github.com/OSCARJFB
#	
#	MIT License
#	Copyright (c) 2023 Oscar Bergström

cc = gcc
cflags = -Wall -Wextra -Werror -pedantic

main:
	$(cc) main.c text.c $(cflags) -lncurses -o main.o
